### ISSUE TITLE
create a route to check if user exists

### ISSUE THREAD

**Issue by gitmank** [gitmank/minimaList#2]
it should respond with 0 or 1 + the status code only!

**Comment by Manoharvuradi** [comment]
Hello @gitmank iam new to opensource, I would like to work on this issue. I literally didn't understood the issue. can tell me the prerequisites to solve this issue, so that I would like to work on.

**Comment by gitmank** [comment]
@Manoharvuradi 
Sure! If you go to [```minimalist-api/index.js```](https://github.com/gitmank/minimaList/blob/e21c5654835e6fa7f9d56a0d6d5ed57faff95f2a/minimalist-api/index.js) you'll find server routes like this -
```js
// signup route
app.post('/signup', (req, res) => authenticator.signup(req, res, bcrypt, User));
```
This will lead to a controller function in [```minimalist-api/controllers/authenticator.js```](https://github.com/gitmank/minimaList/blob/e21c5654835e6fa7f9d56a0d6d5ed57faff95f2a/minimalist-api/controllers/authenticator.js) which looks like
```js
const signup = async (req, res, bcrypt, User) => {
    // check frontend key
    // get hashed password
    // create user
    let temp = new User({
        username:       req.body.username,
        password:       hashedPassword,
    })
    // save user to DB
    temp.save((error, data) => {
        if(!error)
            res.status(200).send(JSON.stringify(data));
        else
            res.status(400).end('invalid');
    })
}
```
I want someone to make similar routes ```/userExists``` and ```/teamCodeExists``` using express which will query for the username and teamcode using mongoose and respond with 
```js
res.status(200).end('1') // if a user or team exists 
res.status(404).end('0') //if no such user or team is found
```
I'm making this a detailed explanation because there are two similar issues like this and if you are interested I could open more. Should I assign this to you?

**Comment by Manoharvuradi** [comment]
Don't assign to me now , I would like to do some research on this because this is something look like new to me and i will let you know when i can do this.

**Comment by Manoharvuradi** [comment]
So, I believe now I have to create one more controller to check weather /userExists or not?

**Comment by gitmank** [comment]
yes just a function in ```authenticator.js```

**Comment by gitmank** [comment]
I've started working on this route because I need it urgently, here is another similar issue that is still available - [check if teamcode exists](https://github.com/gitmank/minimaList/issues/3)
